parameters:
    main:
        # Common hyperparameters
        simulator: 'global'
        env: 'warehouse'
        obs_size: 88
        rollout_steps: 8
        num_actions: 4
        name: 'mini-warehouse-memory'
        hidden_size: 256
        hidden_size_2: 256
        hidden_memory_size: 256
        seq_len: 32
        num_workers: 8
        epsilon: 0.1
        beta: 0.01
        render: False
        policy: 'IAMGRUPolicy'
        load_policy: False
        framestack: False
        # dset: [49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68]
        dset: [64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87]
        # dset: [49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72]
        dset_size: 0
        # dset: [1, 2, 3, 4, 5, 7, 13, 14, 20, 21, 27, 28, 31, 32, 34, 35, 41, 43, 44, 45, 46, 47, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68]
        # dset: [25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36]
        # dset: null