parameters:
    main:
        # Common hyperparameters
        simulator: 'global'
        env: 'minigrid'
        obs_size: 49
        rollout_steps: 8
        num_actions: 6
        name: 'MiniGrid-RedBlueDoors-6x6-v0'
        hidden_size: 192
        hidden_size_2: 256
        seq_len: 32
        num_workers: 8
        epsilon: 0.1
        beta: 0.01
        render: False
        policy: 'GRUPolicy'
        load_policy: False
        framestack: False
        total_steps: 1.0e+6
        # eval_freq: 5.0e+4