parameters:
    main:
        # Common hyperparameters
        simulator: 'global'
        env: 'minigrid'
        obs_size: 50
        rollout_steps: 32
        num_actions: 6
        name: 'MiniGrid-RedBlueDoors-6x6-v0'
        hidden_size: 64
        hidden_size_2: 128
        hidden_memory_size: 64
        seq_len: 32
        num_workers: 8
        epsilon: 0.1
        beta: 0.01
        render: False
        policy: 'IAMGRUPolicy'
        load_policy: False
        framestack: False
        dset_size: 0
        dset: [49]
        total_steps: 1.0e+6
        attention_size: 32
        temperature: 0.01