parameters:
    main:
        # Common hyperparameters
        simulator: 'global'
        env: 'traffic'
        obs_size: 236
        rollout_steps: 64
        num_actions: 2
        name: 'traffic'
        hidden_size: 256
        hidden_size_2: 256
        hidden_memory_size: 256
        seq_len: 32
        num_workers: 8
        epsilon: 0.1
        beta: 0.01
        render: False
        policy: 'IAMGRUPolicy'
        load_policy: False
        framestack: False            
        dset_size: 0
        dset: [0, 1, 2, 3, 4]  
        # dset: null